# Generated by Django 5.1.4 on 2025-01-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('app_name', models.CharField(max_length=255, verbose_name='App Name')),
                ('game_package_name', models.CharField(max_length=255, verbose_name='Game Package Name')),
                ('app_version', models.CharField(default='1.0.0', max_length=100, verbose_name='App Version')),
                ('app_version_bundle', models.PositiveIntegerField(default=1, verbose_name='app version bundle')),
                ('last_bundle_version', models.PositiveIntegerField(default=1, verbose_name='Last bundle version')),
                ('minimum_supported_bundle_version', models.PositiveIntegerField(default=1, verbose_name='minimum supported bundle version')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance mode')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
