# Generated by Django 5.1.4 on 2025-01-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Currency Name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='currencies', verbose_name='Currency Icon')),
                ('config', models.JSONField(blank=True, null=True, verbose_name='Currency Config')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
